				</div>

			<!-- Main -->
				<div class="wrapper">
					<div class="container" id="main">

						<!-- Content -->
							<article id="content">
								<header>
									<h2>¿Quiénes Somos?</h2>
									<p>Kamila Iluminación Residencial</p>
								</header>
								<a href="#" class="image featured"><img src="../images/quien_Logo_Kamila.png" alt="" /></a>
								<h2>MISION</h2>	
								<p>En Kamila Iluminación Residencial nuestra misión es ser el fabricante de lámparas, candiles y plafones decorativos residenciales predilecto de nuestros clientes; para ello contamos con una diversidad en estilos y formas de tipo neoclásico y contemporáneo.</p>
								<br>
								<h2>VISION</h2>
								<p>En Kamila Iluminación Residencial nuestra visión es ofrecer productos elaborados por mexicanos y con materiales mexicanos los cuales cumplen con los estándares de alta calidad, eficiencia y diseño inigualable, por ello somos un modelo exitoso y competitivo a nivel local con enfoque de expansión a mercados internacionales.</p>
							</article>