<!-- Footer -->
				<div id="footer-wrapper">
					<div id="footer" class="container">
						<header class="major">
							<h2>Contáctanos</h2>
							<p>Te ofrecemos, asesoría profesional.</p>
						</header>
						<div class="row">
							<section class="6u 12u(narrower)">
								<form method="post" action="contacto.php">
									<div class="row 50%">
										<div class="6u 12u(mobile)">
											<input name="txtNombre" placeholder="Nombre" type="text" />
										</div>
										<div class="6u 12u(mobile)">
											<input name="txtCorreo" placeholder="Correo" type="text" />
										</div>
									</div>
									<div class="row 50%">
										<div class="12u">
											<textarea name="txtMensaje" placeholder="Mensaje"></textarea>
										</div>
									</div>
									<div class="row 50%">
										<div class="12u">
											<ul class="actions">
												<li><input type="submit" value="Enviar" /></li>
												<li><input type="reset" value="Limpiar" /></li>
											</ul>
										</div>
									</div>
								</form>
							</section>
							<section class="6u 12u(narrower)">
								<div class="row 0%">
									<ul class="divided icons 6u 12u(mobile)">
										
										<li class="icon fa-facebook"><a href="#"><span class="extra">facebook.com/</span>kamila</a></li>
										<li class="icon fa-youtube"><a href="#"><span class="extra">youtube.com/</span>kamila</a></li>
										
										<!-- <li class="icon fa-dribbble"><a href="#"><span class="extra">dribbble.com/</span>kamila</a></li> -->
									</ul>
									<ul class="divided icons 6u 12u(mobile)">
										<!-- <li class="icon fa-instagram"><a href="#"><span class="extra">instagram.com/</span>kamila</a></li> -->
										<li class="icon fa-twitter"><a href="#"><span class="extra">twitter.com/</span>kamila</a></li>
										<!-- <li class="icon fa-pinterest"><a href="#"><span class="extra">pinterest.com/</span>kamila</a></li> -->
									</ul>
								</div>
							</section>
						</div>
					</div>
					<div id="copyright" class="container">
						<ul class="menu">
							<li>&copy; kamila. Todos los derechos reservados.</li><li>Diseñado por: <a href="#">kamila</a></li>
						</ul>
					</div>
				</div>

		</div>

		<!-- Scripts -->

		<script src="../assets/js/setup.js"></script>

		

			<script src="../assets/js/jquery.min.js"></script>
			<script src="../assets/js/jquery.dropotron.min.js"></script>
			<script src="../assets/js/skel.min.js"></script>
			<script src="../assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="../assets/js/main.js"></script>




	</body>
</body>
</html>