<!DOCTYPE html>
<!-- Este es un diseño original de VELTOSYSTEM.COM -->
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

	<title>Kamila Iluminación Residencial</title>

	<link rel="stylesheet" href="../assets/css/animate.css" />
	<link rel="stylesheet" href="../assets/css/main.css" />
	
	<link rel="stylesheet" href="../assets/css/xzoom.css">
	<script type="text/javascript" src="../assets/js/jquery.js"></script>
	<script type="text/javascript" src="../assets/js/xzoom.min.js"></script>
  	<script type="text/javascript" src="../assets/hammer.js/1.0.5/jquery.hammer.min.js"></script>
  	<style>
  		.imgX{
  			max-width: 400px;
  		}
  	</style>
</head>