				<section class="container">
						<header class="major">
							<p>¡Nuestro productos más vendidos!</p>
						</header>
				</section>
				<div class="row features">
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured"><img src="../images/ultimo237.jpg" alt="" /></a>
								</div>
								<header>
									<h3>PLAFON KAMI</h3>
								</header>
								<p>MOD. 237</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="../images/ultimo240.jpg" alt="" /></a>
								</div>
								<header>
									<h3>COLGANTE KAMI</h3>
								</header>
								<p>MOD. 240</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="../images/ultimo101.jpg" alt="" /></a>
								</div>
								<header>
									<h3>LAMPARA FLORENCIA</h3>
								</header>
								<p>MOD. 101</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>
						</div>
					</div>
				</div>